version: '3.8'
services:
  tomcat:
    image: tomcat:10.1
    ports:
     - "8000:8080"
    volumes:
      - ./target/cinema.war:/usr/local/tomcat/webapps/cinema.war
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
